version: '3.2'
services:
  nginx:
    image: nginx:1.17-alpine
    ports:
      - "80:80"
    volumes:
      - .:/app:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /app
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - .:/app:delegated
    working_dir: /app
